name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  pages: write

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check formatting

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/node-setup@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format
  tests:
    name: Run tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/node-setup@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  deploy:
    needs: [format, tests]
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
